import './providers'
import '@modules/admins/providers'
import '@modules/media/providers'
import '@modules/references/providers'
import '@modules/rocks/providers'
import '@modules/buildings/providers'
